### PR TITLE
Tidy readme

### PR DESCRIPTION
**Pull request by DavidOliver**
Attempts to make certain information clearer and fixes some spelling and grammar.

- [x] Please check the 'Force download' section especially carefully as I'm not certain I've correctly understood the original version or accurately conveyed the specifics. I changed the wording partly because I suspect the orginal isn't technically accurate: the rewrite rule does pass all URL query parameters to JIT (with `.+`), so I think it's JIT that chooses to ignore them?

### CODE REVIEW

**Comment by nitriques** [comment]
>  the rewrite rule does pass all URL query parameters to JIT (with .+), so I think it's JIT that chooses to ignore them?

Under Apache, it does not. You need to add `&%{QUERY_STRING}` to the rewritten url, as we do for Symphony's rewrite, in order to get it. And that's good.

So that part would have to be rewritten. Thanks for the review: am I not a native english speaker and I am pretty sure you knew it just by reading what I type ;)

**Comment by DavidOliver** [comment]
Are you saying that Apache itself strips off URL query string parameters
when (.+) is used? That doesn't seem right to me.

I understand that JIT needs the extra rewrite rule, regardless.

**Comment by nitriques** [comment]
> Are you saying that Apache itself strips off URL query string parameters
when (.+) is used? That doesn't seem right to me.

At least on my dev box, it does. $_GET only contains mode and param: any other value passed with ? at the end of the url gets rejected.

**Comment by michael-e** [comment]
Existing query strings are discarded by an Apache `RewriteRule`. If you want to include a query string in the rewritten URL, you can either do it manually (using `%{QUERY_STRING}` or combine old and new query strings automatically using the `QSA` flag.

See here: https://httpd.apache.org/docs/current/rewrite/flags.html#flag_qsa

**Comment by DavidOliver** [comment]
I see - thanks for explaining that. I've now corrected the note.

**Comment by nitriques** [comment]
LGTM! 

@michael-e Thanks for the `QSA` bit.

Please let me merge it in: I use the squash commit process which makes the logs easier to read.

**Pull request merged**
