### PR TITLE
Jit renderer

### PR DESCRIPTION
**Pull request by brendo**
This pull request (and branch) is a major overhaul to the architecture of JIT. Instead of a standalone script, JIT is simply another Renderer which inherits all Symphony functionality. This was made possible by Symphony 2.5, which added the `ModifySymphonyLauncher` delegate. This alleviates the major limitation of JIT in that it can now use delegates.

I believe this change would make it possible to fix the following by adding in delegates, or with minor changes to the code:

- Added other modes easily as they can be dropped into `workspace/jit-image-manipulation/filters`, #73
- Adding different cache types, #69
- Allowing image retrieval to come from different sources, #97

The code in this pull request is far from release quality, but I've pushed up in response to [the comment](https://github.com/symphonycms/symphony-2/issues/2266#issuecomment-68440077) by @jensscherbl that others could probably run with this better than I can. Math and image manipulation are not my strengths, so I'm happy for interested parties to carry on this work and work towards a 2.0 release!

### CODE REVIEW

**Comment by jensscherbl** [comment]
The launcher thing is interesting. I thought about another approach a while ago and would like to hear your opinion on that.

What if we reuse existing Symphony functionality for this? Using pages with an image page type, URL parameter and image data source to create recipes?

Modifications could then be defined on a data source level, similar to what we're discussing for text formatters.

**Comment by brendo** [comment]
> What if we reuse existing Symphony functionality for this? Using pages with an image page type, URL parameter and image data source to create recipes?
> 
> Modifications could then be defined on a data source level, similar to what we're discussing for text formatters.

Interesting. Seems a little cumbersome though? The whole Symphony stack has to be loaded to process an image.

**Comment by jensscherbl** [comment]
> The whole Symphony stack has to be loaded to process an image.

Wouldn't that be the case anyway for using the ModifySymphonyLauncher delegate?

But yeah, I guess you're right, would be a little cumbersome.

**Comment by bernardodiasc** [comment]
This is great!

**Comment by jonmifsud** [comment]
@brendo just noticed this - if I understand correctly at this point this does exactly the same thing as JIT currently does right now. And would need to be extended through delegates to tackle the issues you listed correct? If so I can have a look to see if it would help close #97 as I had to add a few other functions when extending the Image class such as a `__clone` function though that could be added to the main class I presume.

**Comment by brendo** [comment]
> And would need to be extended through delegates to tackle the issues you listed correct?

Yeah correct :)

**Comment by nitriques** [comment]
+1000 in this thing @brendo

**Comment by nitriques** [comment]
Merged as https://github.com/symphonycms/jit_image_manipulation/compare/0f72a2c...18a2b02

Rebased is identical to original: https://github.com/symphonycms/jit_image_manipulation/compare/3629d85..2d8ed7d...0f72a2c..18a2b02

**Pull request closed without merging**
