### PR TITLE
Error handling and compatibility with alternate servers

### PR DESCRIPTION
**Pull request by siimsoni**
Better handling in environments with no .htaccess present (for example Nginx server).
Updated handling error conditions to display relevant error messages.

### CODE REVIEW

**Comment by nitriques** [comment]
LGTM.

@brendo wanna test ?

**Comment by brendo** [comment]
Ideally the `HtAccess` class needs to be commented and should follow at least PSR-1 (and optimally PSR-2).

Concept is ok though.

**Comment by siimsoni** [comment]
The irony how I was avoiding PSR to keep things consistent... I will change it :-)

**Comment by siimsoni** [comment]
I have updated the `HTAccess` class to PSR standard.

**Comment by nitriques** [comment]
Rebased and merged in `integration` as 7aaf6ac

**Pull request closed without merging**
